### ISSUE TITLE
Interpret Oracle responses

### ISSUE THREAD

**Issue by aaronleopold** [weatherdb/weatherdb#16]
Oracle queries have a nested array return structure, I would look into using something like this:

https://www.papaparse.com/docs#strings

to allow you to maybe do something like:

```javascript
var resultsAsString = Papa.unparse({
	"fields": ["Column 1", "Column 2"],
	"data": [
		["foo", "bar"],
		["abc", "def"]
	]
});

const queryResults = Papa.readString(resultsAsString, { header: true }); // arr of objects
```

**Comment by andrewgarmon** [comment]
Closing issues, oracle response can be passed directly to charts
